spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProMegaEnergie
    username: admin
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: uanemaro216@gmail.com
    password: hgze mqkn dbht gpzh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true